-- Create phong (room) table
CREATE TABLE IF NOT EXISTS phong (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ma_phong VARCHAR(128) NOT NULL UNIQUE,
  toa_nha_id BIGINT NULL,
  khu_id BIGINT NULL,
  loai_phong_id BIGINT NULL,
  so_giuong INT NULL,
  trang_thai VARCHAR(64) NULL,
  mo_ta VARCHAR(1024) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

